<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Sushi\Sushi;

class DecorationIcon extends Model
{
    use Sushi;

    protected $rows = [
        ['value' => 'ph:t-shirt-bold', 'slug' => 't-shirt-bold', 'label' => 'T-Shirt', 'status' => 'Active', 'group' => 'clothing'],
        ['value' => 'ph:chat-circle-bold', 'slug' => 'chat-circle-bold', 'label' => 'Chat', 'status' => 'Active', 'group' => 'communication'],
        ['value' => 'ph:envelope-bold', 'slug' => 'envelope-bold', 'label' => 'Envelope', 'status' => 'Active', 'group' => 'communication'],
        ['value' => 'ph:phone-bold', 'slug' => 'phone-bold', 'label' => 'Phone', 'status' => 'Active', 'group' => 'communication'],
        ['value' => 'ph:book-bold', 'slug' => 'book-bold', 'label' => 'Book', 'status' => 'Active', 'group' => 'education'],
        ['value' => 'ph:book-open-bold', 'slug' => 'book-open-bold', 'label' => 'Book Open', 'status' => 'Active', 'group' => 'education'],
        ['value' => 'ph:books-bold', 'slug' => 'books-bold', 'label' => 'Books', 'status' => 'Active', 'group' => 'education'],
        ['value' => 'ph:graduation-cap-bold', 'slug' => 'graduation-cap-bold', 'label' => 'Graduation', 'status' => 'Active', 'group' => 'education'],
        ['value' => 'ph:lightbulb-bold', 'slug' => 'lightbulb-bold', 'label' => 'Lightbulb', 'status' => 'Active', 'group' => 'education'],
        ['value' => 'ph:student-bold', 'slug' => 'student-bold', 'label' => 'Student', 'status' => 'Active', 'group' => 'education'],
        ['value' => 'ph:film-strip-bold', 'slug' => 'film-strip-bold', 'label' => 'Film', 'status' => 'Active', 'group' => 'entertainment'],
        ['value' => 'ph:game-controller-bold', 'slug' => 'game-controller-bold', 'label' => 'Game', 'status' => 'Active', 'group' => 'entertainment'],
        ['value' => 'ph:music-note-bold', 'slug' => 'music-note-bold', 'label' => 'Music', 'status' => 'Active', 'group' => 'entertainment'],
        ['value' => 'ph:newspaper-bold', 'slug' => 'newspaper-bold', 'label' => 'Newspaper', 'status' => 'Active', 'group' => 'entertainment'],
        ['value' => 'ph:paint-brush-bold', 'slug' => 'paint-brush-bold', 'label' => 'Paint Brush', 'status' => 'Active', 'group' => 'entertainment'],
        ['value' => 'ph:party-popper-bold', 'slug' => 'party-popper-bold', 'label' => 'Party Popper', 'status' => 'Active', 'group' => 'entertainment'],
        ['value' => 'ph:television-bold', 'slug' => 'television-bold', 'label' => 'Television', 'status' => 'Active', 'group' => 'entertainment'],
        ['value' => 'ph:arrow-circle-down-bold', 'slug' => 'arrow-circle-down-bold', 'label' => 'Arrow Down', 'status' => 'Active', 'group' => 'finance'],
        ['value' => 'ph:bank-bold', 'slug' => 'bank-bold', 'label' => 'Bank', 'status' => 'Active', 'group' => 'finance'],
        ['value' => 'ph:calculator-bold', 'slug' => 'calculator-bold', 'label' => 'Calculator', 'status' => 'Active', 'group' => 'finance'],
        ['value' => 'ph:chart-bar-bold', 'slug' => 'chart-bar-bold', 'label' => 'Chart Bar', 'status' => 'Active', 'group' => 'finance'],
        ['value' => 'ph:chart-line-bold', 'slug' => 'chart-line-bold', 'label' => 'Chart Line', 'status' => 'Active', 'group' => 'finance'],
        ['value' => 'ph:chart-pie-bold', 'slug' => 'chart-pie-bold', 'label' => 'Chart Pie', 'status' => 'Active', 'group' => 'finance'],
        ['value' => 'ph:coin-bold', 'slug' => 'coin-bold', 'label' => 'Coin', 'status' => 'Active', 'group' => 'finance'],
        ['value' => 'ph:coins-bold', 'slug' => 'coins-bold', 'label' => 'Coins', 'status' => 'Active', 'group' => 'finance'],
        ['value' => 'ph:credit-card-bold', 'slug' => 'credit-card-bold', 'label' => 'Credit Card', 'status' => 'Active', 'group' => 'finance'],
        ['value' => 'ph:currency-circle-dollar-bold', 'slug' => 'currency-circle-dollar-bold', 'label' => 'Dollar Circle', 'status' => 'Active', 'group' => 'finance'],
        ['value' => 'ph:currency-dollar-bold', 'slug' => 'currency-dollar-bold', 'label' => 'Dollar', 'status' => 'Active', 'group' => 'finance'],
        ['value' => 'ph:hand-coin-bold', 'slug' => 'hand-coin-bold', 'label' => 'Hand Coin', 'status' => 'Active', 'group' => 'finance'],
        ['value' => 'ph:money-bold', 'slug' => 'money-bold', 'label' => 'Money', 'status' => 'Active', 'group' => 'finance'],
        ['value' => 'ph:percent-bold', 'slug' => 'percent-bold', 'label' => 'Percent', 'status' => 'Active', 'group' => 'finance'],
        ['value' => 'ph:piggy-bank-bold', 'slug' => 'piggy-bank-bold', 'label' => 'Piggy Bank', 'status' => 'Active', 'group' => 'finance'],
        ['value' => 'ph:receipt-bold', 'slug' => 'receipt-bold', 'label' => 'Receipt', 'status' => 'Active', 'group' => 'finance'],
        ['value' => 'ph:scales-bold', 'slug' => 'scales-bold', 'label' => 'Scales', 'status' => 'Active', 'group' => 'finance'],
        ['value' => 'ph:shield-check-bold', 'slug' => 'shield-check-bold', 'label' => 'Shield Check', 'status' => 'Active', 'group' => 'finance'],
        ['value' => 'ph:trend-down-bold', 'slug' => 'trend-down-bold', 'label' => 'Trend Down', 'status' => 'Active', 'group' => 'finance'],
        ['value' => 'ph:trend-up-bold', 'slug' => 'trend-up-bold', 'label' => 'Trend Up', 'status' => 'Active', 'group' => 'finance'],
        ['value' => 'ph:wallet-bold', 'slug' => 'wallet-bold', 'label' => 'Wallet', 'status' => 'Active', 'group' => 'finance'],
        ['value' => 'ph:barbell-bold', 'slug' => 'barbell-bold', 'label' => 'Barbell', 'status' => 'Active', 'group' => 'health'],
        ['value' => 'ph:first-aid-bold', 'slug' => 'first-aid-bold', 'label' => 'First Aid', 'status' => 'Active', 'group' => 'health'],
        ['value' => 'ph:heart-beat-bold', 'slug' => 'heart-beat-bold', 'label' => 'Heart Beat', 'status' => 'Active', 'group' => 'health'],
        ['value' => 'ph:heart-bold', 'slug' => 'heart-bold', 'label' => 'Heart', 'status' => 'Active', 'group' => 'health'],
        ['value' => 'ph:heart-plus-bold', 'slug' => 'heart-plus-bold', 'label' => 'Heart Plus', 'status' => 'Active', 'group' => 'health'],
        ['value' => 'ph:pill-bold', 'slug' => 'pill-bold', 'label' => 'Pill', 'status' => 'Active', 'group' => 'health'],
        ['value' => 'ph:pills-bold', 'slug' => 'pills-bold', 'label' => 'Pills', 'status' => 'Active', 'group' => 'health'],
        ['value' => 'ph:stethoscope-bold', 'slug' => 'stethoscope-bold', 'label' => 'Stethoscope', 'status' => 'Active', 'group' => 'health'],
        ['value' => 'ph:broom-bold', 'slug' => 'broom-bold', 'label' => 'Broom', 'status' => 'Active', 'group' => 'housing'],
        ['value' => 'ph:building-bold', 'slug' => 'building-bold', 'label' => 'Building', 'status' => 'Active', 'group' => 'housing'],
        ['value' => 'ph:house-bold', 'slug' => 'house-bold', 'label' => 'House', 'status' => 'Active', 'group' => 'housing'],
        ['value' => 'ph:key-bold', 'slug' => 'key-bold', 'label' => 'Key', 'status' => 'Active', 'group' => 'housing'],
        ['value' => 'ph:lamp-bold', 'slug' => 'lamp-bold', 'label' => 'Lamp', 'status' => 'Active', 'group' => 'housing'],
        ['value' => 'ph:coffee-bold', 'slug' => 'coffee-bold', 'label' => 'Coffee', 'status' => 'Active', 'group' => 'lifestyle'],
        ['value' => 'ph:cup-bold', 'slug' => 'cup-bold', 'label' => 'Cup', 'status' => 'Active', 'group' => 'lifestyle'],
        ['value' => 'ph:fork-knife-bold', 'slug' => 'fork-knife-bold', 'label' => 'Food', 'status' => 'Active', 'group' => 'lifestyle'],
        ['value' => 'ph:hamburger-bold', 'slug' => 'hamburger-bold', 'label' => 'Hamburger', 'status' => 'Active', 'group' => 'lifestyle'],
        ['value' => 'ph:pizza-bold', 'slug' => 'pizza-bold', 'label' => 'Pizza', 'status' => 'Active', 'group' => 'lifestyle'],
        ['value' => 'ph:gear-bold', 'slug' => 'gear-bold', 'label' => 'Gear', 'status' => 'Active', 'group' => 'misc'],
        ['value' => 'ph:people-bold', 'slug' => 'people-bold', 'label' => 'People', 'status' => 'Active', 'group' => 'misc'],
        ['value' => 'ph:plus-circle-bold', 'slug' => 'plus-circle-bold', 'label' => 'Plus Circle', 'status' => 'Active', 'group' => 'misc'],
        ['value' => 'ph:scissors-bold', 'slug' => 'scissors-bold', 'label' => 'Scissors', 'status' => 'Active', 'group' => 'misc'],
        ['value' => 'ph:toolbox-bold', 'slug' => 'toolbox-bold', 'label' => 'Toolbox', 'status' => 'Active', 'group' => 'misc'],
        ['value' => 'ph:wrench-bold', 'slug' => 'wrench-bold', 'label' => 'Wrench', 'status' => 'Active', 'group' => 'misc'],
        ['value' => 'ph:flower-bold', 'slug' => 'flower-bold', 'label' => 'Flower', 'status' => 'Active', 'group' => 'nature'],
        ['value' => 'ph:leaf-bold', 'slug' => 'leaf-bold', 'label' => 'Leaf', 'status' => 'Active', 'group' => 'nature'],
        ['value' => 'ph:tree-bold', 'slug' => 'tree-bold', 'label' => 'Tree', 'status' => 'Active', 'group' => 'nature'],
        ['value' => 'ph:cat-bold', 'slug' => 'cat-bold', 'label' => 'Cat', 'status' => 'Active', 'group' => 'pets'],
        ['value' => 'ph:dog-bold', 'slug' => 'dog-bold', 'label' => 'Dog', 'status' => 'Active', 'group' => 'pets'],
        ['value' => 'ph:bag-bold', 'slug' => 'bag-bold', 'label' => 'Bag', 'status' => 'Active', 'group' => 'shopping'],
        ['value' => 'ph:gift-bold', 'slug' => 'gift-bold', 'label' => 'Gift', 'status' => 'Active', 'group' => 'shopping'],
        ['value' => 'ph:gifts-bold', 'slug' => 'gifts-bold', 'label' => 'Gifts', 'status' => 'Active', 'group' => 'shopping'],
        ['value' => 'ph:shopping-bag-bold', 'slug' => 'shopping-bag-bold', 'label' => 'Shopping Bag', 'status' => 'Active', 'group' => 'shopping'],
        ['value' => 'ph:shopping-bags-bold', 'slug' => 'shopping-bags-bold', 'label' => 'Shopping Bags', 'status' => 'Active', 'group' => 'shopping'],
        ['value' => 'ph:shopping-cart-bold', 'slug' => 'shopping-cart-bold', 'label' => 'Shopping Cart', 'status' => 'Active', 'group' => 'shopping'],
        ['value' => 'ph:storefront-bold', 'slug' => 'storefront-bold', 'label' => 'Storefront', 'status' => 'Active', 'group' => 'shopping'],
        ['value' => 'ph:tag-bold', 'slug' => 'tag-bold', 'label' => 'Tag', 'status' => 'Active', 'group' => 'shopping'],
        ['value' => 'ph:computer-tower-bold', 'slug' => 'computer-tower-bold', 'label' => 'Computer Tower', 'status' => 'Active', 'group' => 'technology'],
        ['value' => 'ph:device-mobile-bold', 'slug' => 'device-mobile-bold', 'label' => 'Mobile', 'status' => 'Active', 'group' => 'technology'],
        ['value' => 'ph:device-tablet-bold', 'slug' => 'device-tablet-bold', 'label' => 'Tablet', 'status' => 'Active', 'group' => 'technology'],
        ['value' => 'ph:laptop-bold', 'slug' => 'laptop-bold', 'label' => 'Laptop', 'status' => 'Active', 'group' => 'technology'],
        ['value' => 'ph:monitor-bold', 'slug' => 'monitor-bold', 'label' => 'Monitor', 'status' => 'Active', 'group' => 'technology'],
        ['value' => 'ph:smartphone-bold', 'slug' => 'smartphone-bold', 'label' => 'Smartphone', 'status' => 'Active', 'group' => 'technology'],
        ['value' => 'ph:airplane-bold', 'slug' => 'airplane-bold', 'label' => 'Airplane', 'status' => 'Active', 'group' => 'transport'],
        ['value' => 'ph:bus-bold', 'slug' => 'bus-bold', 'label' => 'Bus', 'status' => 'Active', 'group' => 'transport'],
        ['value' => 'ph:car-bold', 'slug' => 'car-bold', 'label' => 'Car', 'status' => 'Active', 'group' => 'transport'],
        ['value' => 'ph:gas-pump-bold', 'slug' => 'gas-pump-bold', 'label' => 'Gas Pump', 'status' => 'Active', 'group' => 'transport'],
        ['value' => 'ph:motorcycle-bold', 'slug' => 'motorcycle-bold', 'label' => 'Motorcycle', 'status' => 'Active', 'group' => 'transport'],
        ['value' => 'ph:train-bold', 'slug' => 'train-bold', 'label' => 'Train', 'status' => 'Active', 'group' => 'transport'],
        ['value' => 'ph:backpack-bold', 'slug' => 'backpack-bold', 'label' => 'Backpack', 'status' => 'Active', 'group' => 'travel'],
        ['value' => 'ph:suitcase-bold', 'slug' => 'suitcase-bold', 'label' => 'Suitcase', 'status' => 'Active', 'group' => 'travel'],
        ['value' => 'ph:drop-bold', 'slug' => 'drop-bold', 'label' => 'Water', 'status' => 'Active', 'group' => 'utilities'],
        ['value' => 'ph:fire-bold', 'slug' => 'fire-bold', 'label' => 'Fire', 'status' => 'Active', 'group' => 'utilities'],
        ['value' => 'ph:lightning-bold', 'slug' => 'lightning-bold', 'label' => 'Lightning', 'status' => 'Active', 'group' => 'utilities'],
        ['value' => 'ph:wifi-bold', 'slug' => 'wifi-bold', 'label' => 'WiFi', 'status' => 'Active', 'group' => 'utilities'],
        ['value' => 'ph:briefcase-bold', 'slug' => 'briefcase-bold', 'label' => 'Briefcase', 'status' => 'Active', 'group' => 'work'],
        ['value' => 'ph:handshake-bold', 'slug' => 'handshake-bold', 'label' => 'Handshake', 'status' => 'Active', 'group' => 'work'],
    ];
}
